@cms.server_HostAddress = http://localhost:5216
@cms.server_CarController={{@cms.server_HostAddress}}/Car

GET {{cms.server_CarController}}/getCarList/
Accept: application/json


GET {{cms.server_CarController}}/GetCarDetailByBrandName/
Accept: application/json

GET {{cms.server_CarController}}/getCarModelByBrandClassName/
Accept: application/json

POST {{cms.server_CarController}}/addeditCar/
Accept: application/json

POST {{cms.server_CarController}}/addeditCarModel/
Accept: application/json
Content-Type: multipart/form-data
###
